<<<<<<< Updated upstream:app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from './components/nav/nav'
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono, Sawarabi_Gothic, Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Title from "./components/title"
>>>>>>> Stashed changes:app/layout.tsx

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< Updated upstream:app/layout.js
export const metadata = {
  title: "Sääntieđotus | Været",
  description: "Generated by create next app",
=======
const sawarabiGothic = Sawarabi_Gothic({
  weight: "400",
  variable: "--font-sawarabi-gothic",
  subsets: ["latin"],
})

const poppins = Poppins({
  weight: "400",
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sääntieđotus",
  description: "Værmeldingen på kvensk",
>>>>>>> Stashed changes:app/layout.tsx
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< Updated upstream:app/layout.js
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
>>>>>>> Stashed changes:app/layout.tsx
        <Nav />
        {children}
      </body>
    </html>
  );
}
